Dispatch info
platanus/the-store1 pull request #1
Opened 2023-08-21 21:01 UTC by mcox5

### Contexto
Se trabajó en agregarle a las compras una compañía de delivery asociada y una fecha de entrega

### Qué se esta haciendo
Se tuvo que crear un modelo de "DeliveryCompany" con las asociaciones respectivas.
Se tuvo que crear y correr una migración que agrega cómo referencia una DeliveryCompany a un Purchase (opcional).
Se generó migración para agregar columna de date a Purchase

#### En particular hay que revisar
Relación entre purchase y DeliveryCompany.

-----------
#### Info Adicional (pantallazos, links, fuentes, etc.)

2023-08-21 21:02 UTC, monkeyci commented on app/models/delivery_company.rb
> +  has_many :purchases
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Rails/HasManyOrHasOneDependent: Specify a :dependent option.

2023-08-22 16:21 UTC, difernandez requested changes
Algunos detalles!

2023-08-22 16:21 UTC, difernandez commented on .ruby-version
> +3.1.0
Dejamos a propósito con solo el minor, para no estar cambiando siempre y que dependa demasiado de lo que tiene cada dev en su ambiente local. Si no te funcionó, probablemente te falte instalar [rbenv-aliases](https://la-guia.platan.us/setup/configuracion_de_tu_entorno_local/tecnologias/ruby#ruby-aliases)

2023-08-22 16:21 UTC, difernandez commented on spec/models/delivery_company_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
agregaría acá el test de factory que te mencioné

2023-08-22 16:21 UTC, difernandez commented on db/migrate/20230821193120_add_delivery_company_to_purchase.rb
> +    add_reference :purchases, :DeliveryCompany, index: {algorithm: :concurrently}
- Acá el DeliveryCompany debería estar en snake_case, si te fijas se creó la columna con este PascalCase
- Siempre que se agregue una referencia, se debería agregar tambn la foreign_key

2023-08-22 16:21 UTC, difernandez commented on db/migrate/20230821203231_add_date_to_purchase.rb
> +    add_column :purchases, :date, :date
`date` quizás es un poco genérico. Es la fecha en que se hizo la compra? La fecha de entrega? Entiendo que es la última, le pondría algo tipo `delivery_date`

2023-08-23 21:02 UTC, difernandez requested changes
un par de detallitos de los tests!

2023-08-23 21:02 UTC, difernandez commented on spec/models/admin_user_spec.rb
> +  end
La idea es que en nuestros prs solo agreguemos tests o arreglemos infracciones de linter de partes del código que estamos tocando, para que el pr sea consistente en incluir cambios relacionados y necesario para una feature (o fix o lo que sea) en particular. Si hay algo en otro lado que falta o está con error de linter, o se arregla en pr aparte de refactor, o queda así hasta que se toque esa parte del código

2023-08-23 21:02 UTC, difernandez commented on spec/models/delivery_company_spec.rb
> +  end
acá la idea sería tener solo un test para ver que la factory sea válida, [como esto](https://apidock.com/rails/ActiveRecord/ConnectionAdapters/SchemaStatements/add_reference#1665-foreign-key-option). Luego, en otro describe de validaciones, irían cosas como lo que tienes acá, pero hay un DSL particular para testear las validaciones comunes, [se ven así](https://github.com/platanus/the-store1/blob/master/spec/models/item_spec.rb#L8)

2023-08-28 15:35 UTC, MarcoNaik approved these changes
💎

2023-08-29 15:10 UTC, difernandez approved these changes

2023-08-30 14:00 UTC, merged