View product
platanus/the-store1 pull request #2
Opened 2023-08-28 13:57 UTC by aerotecnia99

### Contexto
Crear vista para visualizar detalles de un producto, a la cual se puede acceder desde el index de productos clickeando el botón detalles de cada ítem.

### Qué se esta haciendo

- Se agregó un botón "Detalles" en el index de productos.
- Se creó un nuevo componente `item-details.vue` para la vista del producto.
- Se modificó el controlador de items `app/items_controller.rb` y `routes.rb` para enrutar el recurso.

#### En particular hay que revisar
La nueva vista de detalles del producto.

-----------
#### Info Adicional (pantallazos, links, fuentes, etc.)

2023-08-28 13:58 UTC, monkeyci commented on app/javascript/application.js
> +import InlineSvg from 'vue-inline-svg';
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Absolute imports should come before relative imports  import/imports-first

2023-08-29 13:30 UTC, ldlsegovia approved these changes
Se ve bien! quizás Diego te puede dar mejor feedback sobre esta parte que es pro en front.
Algo que sería deseable es que acomodes un poco el estilo para que funcione en otras resoluciones

![image](https://github.com/platanus/the-store1/assets/3026413/753b3a11-4957-4c62-9900-99991dbfc928)

Cuando hacés cosas de front está bueno acompañar la descripción del PR con capturas o mejor aún con gif. Yo suelo usar https://getkap.co/

2023-08-29 13:43 UTC, difernandez commented
@ldlsegovia uh la falta de responsive es mala mia, está asi en el base 😬. Estaba bastante seguro que lo había hecho responsive pero se me debe haber pasado 😅

2023-08-29 13:58 UTC, ldlsegovia commented
> @ldlsegovia uh la falta de responsive es mala mia, está asi en el base 😬. Estaba bastante seguro que lo había hecho responsive pero se me debe haber pasado 😅

ah buena! igual lo decía como sugerencia más que nada. Por eso lo aprobé 👍🏻

2023-08-29 14:27 UTC, difernandez requested changes
buena! algunos detalless

2023-08-29 14:27 UTC, difernandez commented on app/javascript/components/item-list-card.vue
> +        @click="goToItemDetails"
si el `@click` de un botón solo redirige, en verdad debería ser un `<a>` con un href. Eso te permite cosas como abrir el link en otra pestaña, o copiarlo con el menú del botón derecho

2023-08-29 14:27 UTC, difernandez commented on yarn.lock
Me tinca que agregaste la librería con `npm install`, no? Por lo que veo, eso sale en la documentación. Pregunto porque casi todos los cambios en este archivo son cambios en el registro de que se saca, que pasó a ser `npmjs`. Nosotros usamos yarn, entonces cuando un paquete dice `npm install`, en verdad nosotro usamos `yarn add`. Prueba corriendo yarn install, creo que con eso se debería desaparecer estos cambios y volver a `yarnpkg`

2023-08-29 14:27 UTC, difernandez commented on app/javascript/application.js
> +import InlineSvg from 'vue-inline-svg';
aquí hay que corregir lo que dice el mono 👮‍♂️ es mover este import para arriba, antes que los relativos. No recuerdo si está regla es auto-fixeable, pero si lo es, puedes [configurar vscode para que corrija lo que sea auto-fixeable al guardar el archivo](https://la-guia.platan.us/setup/configuracion_de_tu_entorno_local/herramientas/linters#linters:~:text=Puedes%20hacer%20que-,al%20guardar%20un%20archivo,-.js/%20.vue)

2023-08-29 14:27 UTC, difernandez commented on app/javascript/components/item-details.vue
> +          @click="buy"
acá agregaría un `:disabled="loading"` para tratar de evitar que se mande con doble click

2023-08-29 14:27 UTC, difernandez commented on app/javascript/components/item-details.vue
> -import InlineSvg from 'vue-inline-svg';
tratamos de evitar agregar commits en un PR que cambien algo que se toca en un commit anterior del mismo PR. Está bien cuando el cambio es como agregar sobre lo que se hizo en otro commit, onda para ir construyendo una feature de a poco, pero cuando es un cambio que corrige un error del commit anterior, lo que hacemos es agregar ese cambio con un fixup al commit donde se introdujo ese cambio y luego agregarlo a ese commit con un rebase. Seguimos ese mismo procedimiento para aplicar cambios que nos piden en un PR, o si hay que corregir cosas del mono por ejemplo. Con esto queda la historia del PR más limpia y fácil de entender. Te recomendaría cambiarlo para que este cambio se aplique así, para que practiques lo que es los rebase también. [Acá hay un par de links útiles](https://la-guia.platan.us/setup/configuracion_de_proyectos/git#rebase), y si necesitas ayuda me dices tambn

2023-08-30 20:29 UTC, monkeyci commented on app/javascript/components/item-details.vue
> +      class="mb-12 inline-flex items-center rounded-full bg-gray-200 py-2 px-4 text-sm font-normal"
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Invalid Tailwind CSS classnames order  tailwindcss/classnames-order

2023-08-30 20:29 UTC, monkeyci commented on app/javascript/components/item-details.vue
> +          class="w-full rounded-full bg-blue-800 py-2 px-4 text-lg font-bold text-white"
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Invalid Tailwind CSS classnames order  tailwindcss/classnames-order

2023-08-30 20:29 UTC, monkeyci commented on app/javascript/components/item-list-card.vue
> +    <div class="inline-flex h-16 w-full items-start justify-around py-4 px-3">
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Invalid Tailwind CSS classnames order  tailwindcss/classnames-order

2023-08-31 19:18 UTC, difernandez approved these changes
dejo aprobado, pero échale un ojo a los últimos comentarios del mono! Esa es una regla que es muy latera de mantener sin el autofix de eslint

2023-09-01 14:19 UTC, merged