Purchase detail v2
platanus/the-store1 pull request #3
Opened 2023-09-04 20:54 UTC by mcox5

### Contexto
Vista de una compra
### Qué se esta haciendo
Se añadieron las vistas del show de compras (purchase).
#### En particular hay que revisar
Componentes Vue.
Método update en controlador de purchases.
Serializer

-----------
#### Info Adicional (pantallazos, links, fuentes, etc.)

2023-09-04 20:56 UTC, monkeyci commented on app/controllers/app/purchases_controller.rb
> +    @purchases = current_user.purchases.order(created_at: :desc).includes([:item, :delivery_company])
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/LineLength: Line is too long. [101/100]

2023-09-04 20:56 UTC, monkeyci commented on app/javascript/components/purchase-delivery-date-card.vue
> +        <button class="flex h-11 shrink grow basis-0 items-center justify-center gap-1 rounded-lg bg-blue-800 px-4 py-2" @click="updateDate">
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'@click' should be on a new line  vue/max-attributes-per-line

2023-09-04 20:56 UTC, monkeyci commented on app/javascript/components/purchase-list.vue
> +import { computed } from 'vue';
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'computed' is defined but never used  @typescript-eslint/no-unused-vars

2023-09-04 20:56 UTC, monkeyci commented on app/javascript/components/purchase-message.vue
> +      Próximamente podrás ver por acá la fecha de entrega e información de contacto de la empresa que realizará el despacho
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>This line has a length of 123. Maximum allowed is 120  max-len

2023-09-04 20:56 UTC, monkeyci commented on app/javascript/components/purchase-message.vue
> +      Próximamente podrás ver por acá la fecha de entrega e información de contacto de la empresa que realizará el despacho
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>This line has a length of 123. Maximum allowed is 120  vue/max-len

2023-09-04 20:56 UTC, monkeyci commented on app/javascript/utils/date-converter.js
> +  const months = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'];
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>This line has a length of 143. Maximum allowed is 120  max-len

2023-09-04 20:56 UTC, monkeyci commented on app/javascript/utils/date-converter.js
> +  const months = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'];
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>This line has a length of 143. Maximum allowed is 120  vue/max-len

2023-09-04 20:56 UTC, monkeyci commented on app/javascript/components/purchase-list-card.vue
> +import vector from '../../assets/images/icons/vector.png';
🚫 **[tsc]** <2307> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Cannot find module '../../assets/images/icons/vector.png' or its corresponding type declarations.

2023-09-04 20:57 UTC, monkeyci commented on app/controllers/api/internal/purchases_controller.rb
> +    respond_with purchase.update!(purchase_params)
<sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Not covered lines: 17

2023-09-06 12:41 UTC, ldlsegovia commented on app/controllers/app/purchases_controller.rb
> +  def show
https://www.notion.so/platanus/Gu-a-de-Estilo-67506d25082349d9b4128f25f1f81a69#f1e1397fa32642b1b66b6de8e451dbcd 

De acuerdo con la guía de estilos, en app mejor usar `set_purchase` para ser más explícitos 

<img width="748" alt="image" src="https://github.com/platanus/the-store1/assets/3026413/e4444ff8-a7c1-4720-9662-076b764040f7">

2023-09-06 12:41 UTC, ldlsegovia commented on app/controllers/app/purchases_controller.rb
> +    @purchase ||= current_user.purchases.find_by!(id: params[:id])
si las purchases siempre tienen el mismo origen, mejor sacar en un método

```ruby
def purchases
  @purchases ||= current_user.purchases
end
```

para `purchases` está bien usar memoization porque ahí lo usarás indirectamente

2023-09-06 13:05 UTC, difernandez requested changes
buena, harta pega! 👏 dejo varios comentarios, la mayoría chicos igual. Cuéntame no más si tienes dudas con algo, si no se entendió o quieres saber más.
Un detalle importante que mencioné en un comentario pero creo que vale la pena ahondar un poco. Trata de no commitear cosas que después vas a reemplazar después en otro commit. La idea es que los commits de un PR sean la historia de como se va construyendo la feature, pero obviando las cosas que fuiste probando y que cosas cachaste después que era mejor hacerlas de otra manera. Así la historia queda más odenada, fácil de revisar y de entender si se requiere a futuro.
También trata de que los commits sean más atómicos, osea que se relacionen a un solo cambio cohesivo. No me refiero a que un commit sea un cambio a solo un archivo, pero si que todos los cambios de ese commit tengan que ver con una cosa en común, con la descripción del commit digamos

2023-09-06 13:05 UTC, difernandez commented on app/assets/images/icons/vector.png
vector en un nombre medio genérico para un svg. Algo como "arrow-right" (o también se les dice "caret-right" de repente) sería más claro

2023-09-06 13:05 UTC, difernandez commented on app/javascript/components/purchase-list-card.vue
> +    >
para los svg la mayoría de las veces las ponemos como svg inline usando una librería. Ya está en el proyecto, [acá un ejemplo](https://github.com/platanus/the-store1/blob/db30ffa8bb73da648f9dd3ed693a7fbdbce5c92a/app/javascript/components/purchase-list-card.vue#L34). Eso también debería solucionar el problema de tsc de más arriba

2023-09-06 13:05 UTC, difernandez commented on app/javascript/components/purchase-list.vue
> +      :date="'12/12/2022'"
trata de no commitear cosas que después en el mismo PR vas a reemplazar por algo más. Por lo que veo, este date se cambia por el purchase completo después. Trata de commitear ese cambio de una cuando esté listo, para que la historia quede más limpia y sea más fácil leer y revisar después

2023-09-06 13:05 UTC, difernandez commented on app/javascript/components/purchase-message.vue
> +// defineProps<Props>();
se tienen que sacar estos comentarios

2023-09-06 13:05 UTC, difernandez commented on app/javascript/components/purchase-delivery-date-card.vue
> +    <!-- BOTON REAGENDAR -->
Por lo general evitamos comentarios en el código en post de que el código sea autoexplicativo

2023-09-06 13:05 UTC, difernandez commented on app/javascript/components/purchase-delivery-date-card.vue
> +    <!-- REAGENDAR -->
idem comentario

2023-09-06 13:05 UTC, difernandez commented on app/javascript/components/purchase-dispatch-card.vue
> +// defineProps<Props>();
idem sacar comentarios

2023-09-06 13:05 UTC, difernandez commented on app/javascript/api/delivery_company.ts
> +// import api from './index';
idem comentario

2023-09-06 13:05 UTC, difernandez commented on app/assets/images/icons/row.png
ojo que vi que en otro pr de este repo ya se había agregado este ícono y un botón de back, la idea sería no tener esas cosas repetidas

2023-09-06 13:05 UTC, difernandez commented on app/controllers/api/internal/purchases_controller.rb
> +    respond_with purchase.update!(purchase_params)
ojo que el `update!` no retorna el objeto, retorna un booleano. El endpoint debería retornar el objeto

2023-09-06 13:05 UTC, difernandez commented on app/javascript/components/back-button.vue
> +  </button>
el button indica un elemento clickeable, evitaría tenerlo sin que tenga un comportamiento como `@click`. En este caso, como es un link hacia atrás, en verdad debería ser un `<a>` solo, en vez de un anchor con un button dentro

2023-09-06 13:05 UTC, difernandez commented on app/javascript/components/purchase-delivery-date-card.vue
> +const isSheduling = ref(false);
typo: es Scheduling

2023-09-06 13:05 UTC, difernandez commented on app/javascript/components/purchase-delivery-date-card.vue
> +          <div class="text-lg font-bold leading-7">
este div no es necesario, puedes poner estos estilos directo en el button padre

2023-09-06 13:05 UTC, difernandez commented on app/javascript/components/purchase-delivery-date-card.vue
> +          <div class="text-lg font-bold leading-7 text-white">
idem div no necesario

2023-09-06 13:05 UTC, difernandez commented on app/javascript/components/purchase-delivery-date-card.vue
> +          class="flex h-11 shrink grow basis-0 items-center justify-center gap-1 rounded-full px-4 py-2"
creo que podrías reemplazar el `shrink grow basis-0` con `flex-1`

2023-09-06 13:05 UTC, difernandez commented on app/javascript/components/purchase-delivery-date-card.vue
> +          class="flex h-11 shrink grow basis-0 items-center justify-center gap-1 rounded-lg bg-blue-800 px-4 py-2"
idem `flex-1`

2023-09-06 13:05 UTC, difernandez commented on app/javascript/components/purchase-detail.vue
> +    />
me gustó como quedó esto, bien ordenada cada sección con su condición 👌

2023-09-06 13:05 UTC, difernandez commented on app/javascript/components/purchase-dispatch-card.vue
Este archivo no se usa

2023-09-06 13:05 UTC, difernandez commented on app/javascript/utils/date-converter.js
> +export default formatDate;
usaría algo como [el format de date-fns](https://date-fns.org/v2.30.0/docs/format) para algo así

2023-09-06 13:05 UTC, difernandez commented on spec/requests/api/internal/purchases_spec.rb
> +    let(:purchase_id) { purchase.id.to_s }
no es necesario pasarlo a string, se hace automático en la interpolación

2023-09-06 13:05 UTC, difernandez commented on app/javascript/components/purchase-product-card.vue
> +const isDelivered = props.purchase.status !== 'pending';
definiría esto como computed también

2023-09-06 13:05 UTC, difernandez commented on app/javascript/components/purchase-product-card.vue
> +  <div class="inline-flex h-[375px] w-[768px] flex-col items-start justify-start rounded-2xl border border-zinc-500 bg-white shadow">
por lo general tratamos de evitar usar valores custom como el `h-[375px] w-[768px]`. Ideal tratar de que las cosas crezcan y se achiquen según lo que necesiten (sobre todo pensando en mobile/reactividad) usando algo como flex o w-full, o si se necesita un tamaño fijo, usar los que ya vienen con tailwind, el que más se acerque

2023-09-06 13:05 UTC, difernandez commented on app/javascript/components/purchase-product-card.vue
> +        class="h-[300px] w-[300px] rounded-bl-[10px]"
idem acá con los tamaños custom

2023-09-06 13:05 UTC, difernandez commented on app/javascript/components/purchase-product-card.vue
> +          class="inline-flex shrink grow basis-0 items-center justify-start gap-2.5 self-stretch px-8"
idem acá lo de reemplazar `shrink grow basis-0` con `flex-1`

2023-09-11 18:05 UTC, mcox5 commented on app/javascript/utils/date-converter.js
> +export default formatDate;
Se utilizó el método .toLocaleDateString de la librería de Date que viene con JavaScript

2023-09-12 13:05 UTC, mcox5 commented on app/assets/images/icons/row.png
Toda la razon, pasó que la vale agregó uno y yo otro, dejé finalmente el que agrego la vale

2023-09-12 13:07 UTC, mcox5 commented on app/javascript/components/purchase-list.vue
> +      :date="'12/12/2022'"
Ok! perfect se entiende la idea

2023-09-12 13:17 UTC, monkeyci commented on spec/requests/api/internal/purchases_spec.rb
> +    let(:purchase_id) { purchase.id}
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/SpaceInsideBlockBraces: Space missing inside }.

2023-09-14 13:10 UTC, difernandez approved these changes
nice 💯

2023-09-25 14:39 UTC, merged